services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superuser
      POSTGRES_DB: personal_tracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api-service/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d personal_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    image: vanhoadotbui2628/personal-tracker-api
    platform: linux/amd64
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: superuser
      DB_PASSWORD: superuser
      DB_NAME: personal_tracker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api-service:/app
      - /app/node_modules

  frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://13.210.111.152:4000
    image: vanhoadotbui2628/personal-tracker-frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./web-frontend:/app
      - /app/node_modules
      - /app/.next

  dozzle:
    container_name: dozzle-agent-education
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5555:5555"
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_AUTH=false
    command: ["--addr=:5555"] 
    restart: unless-stopped

volumes:
  postgres_data:
